/**
 * Parallel Make
 * CS 241 - Fall 2017
 */

#pragma once
/**
 * this file exists so that we can provide a main method which does a variety of
 * handy things.
 *
 * DO NOT EDIT THIS FILE!
 */

#include <stddef.h>

// entry point for student code
int parmake(char *makefile, size_t num_threads, char **targets);
